### PR TITLE
Added authentication check for post routes

### PR DESCRIPTION
**Pull request by HelioStrike**
Based on [this issue](https://github.com/ShekharReddy4/openmrs-contrib-atlas-node/issues/4). Weirdly, I couldn't test the code I wrote, as the '/login/' route leads to 'http://localhost:8080/authenticate/atlas' which I don't know how to set up. If I can get that url running, I think I could test and confirm whether my code does the job.

### CODE REVIEW

**Comment by cintiadr** [comment]
I don't mind merging this PR at all, but bear in mind that login is _not_ working 💃

**Comment by HelioStrike** [comment]
@cintiadr Since it has to be implemented at some point, I think the PR should be merged. Well, then again, since its my code, I'm quite biased. :P 
What do you think?

**Comment by cintiadr** [comment]
You know what, sure, I'm fairly sure if it broke something, we'll have to fix!

**Comment by HelioStrike** [comment]
Holy moly. I was pretty busy and stressed out yesterday that somehow I forgot that adding the authentication routes might mean that code elsewhere using it may longer be able to do so. Sorry about that.
I hope it didn't break anything, but yup, if anything does break, we'll have to fix. :)

**Comment by cintiadr** [comment]
Well, it's not more broken now than it was before, so it's fine. Not really going to keep me awake at night.

**Comment by dkayiwa** [comment]
@HelioStrike did you see this? https://ci.openmrs.org/browse/ATLAS-ATL-10/log

**Comment by cintiadr** [comment]
That’s on me, @dkayiwa. 

I deleted the staging server.

**Pull request merged**
