### PR TITLE
3.x dockerfile

### PR DESCRIPTION
**Pull request by cintiadr**

### CODE REVIEW

**Comment by cintiadr** [comment]
@agbilotia1998, so these are the changes I did:

  - I moved the bootstrap script into this repo; added it to the docker-compose file. 
  - Added the entrypoint.sh file, which does a silly sleep to make sure the mysql server is up
  - Allowed database config to be done via environment variables
  - Refactored the readme file
  - Used the version of mysql that we have in production
 

Things that are missing, and I'd like you to address in other pull requests:
  - Instead of running 'sleep 30', I'd like wait-for-it script copied inside docker subfolder (https://github.com/vishnubob/wait-for-it), and used to test port 3306 open
  - I'd like the node process to run as non-root user
  
I will check if the database schema is the same that is running in production. 

If you want me to upgrade the mysql server, I'd have to test if upgrade works. I don't want to mix it now.

**Comment by agbilotia1998** [comment]
@cintiadr to test mysql service is up, can we use something like
screenshot-2018-4-6 docker-compose check if mysql connection is ready 1

and in service db
screenshot-2018-4-6 docker-compose check if mysql connection is ready

**Comment by cintiadr** [comment]
I'm sick, so I'm avoiding the laptop today. 

Unfortunately, depends_on condition doesn't work anymore :/

```
depends_on does not wait for db and redis to be “ready” before starting web - only until they have been started. If you need to wait for a service to be ready, see Controlling startup order for more on this problem and strategies for solving it.

Version 3 no longer supports the condition form of depends_on.
```

https://docs.docker.com/compose/compose-file/

https://docs.docker.com/compose/startup-order/

**Comment by cintiadr** [comment]
But the healthcheck is actually great. So +1 for that.

**Comment by agbilotia1998** [comment]
Okay, I will do the required changes. Thanks :)

**Pull request merged**
