### PR TITLE
ATLAS-146: Improve the styling of the Atlas Login page

### PR DESCRIPTION
**Pull request by HelioStrike**
Borrowed code from OpenMRS ID login to make the Atlas login look like it.

JIRA issue: https://issues.openmrs.org/browse/ATLAS-146?jql=project%20%3D%20ATLAS

Screenshot from 2019-06-13 22-21-28

### CODE REVIEW

**Comment by HerbertYiga** [comment]
you can append your  snap shots to the JIRA ticket as advised here https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by HelioStrike** [comment]
@HerbertYiga done :)

**Comment by cintiadr** [comment]
Well, that's _way_ too similar, scarily too identical. 
Can you remove the text at the top ('your openmrsid is the key blablabla') and the footer ('Need help and everything below).

**Comment by HelioStrike** [comment]
@cintiadr done :)

**Comment by HelioStrike** [comment]
@cintiadr 

> Can you remove the text at the top ('your openmrsid is the key blablabla') and the footer ('Need help and everything below).

I believe I pushed the change. Here's the new screen.

Screenshot from 2019-06-16 11-53-43

**Comment by bmamlin** [comment]
@cintiadr, Atlas (like Discourse and Desk.com) had been [configured for SSO](https://github.com/openmrs/openmrs-contrib-id/blob/master/app/user-modules/openmrs-contrib-id-sso/conf.example.js) against OpenMRS ID. Can we still use this (as we are for Talk)? It seems better to leverage OpenMRS ID's login page instead of duplicating it.

**Comment by cintiadr** [comment]
@bmamlin , SSO in ID broke a couple of years ago for both Desk.com and Atlas. To be fair, looking at the whole thing, it's a surprise it's still working for talk, and I'm not going to be surprised when it stops working. We don't maintain the code, we don't have anyone knowledgeable on the security implications of the decisions we took, we don't apply not even security patches to that code. I don't think I can even be bothered to try to understand that, as the person who originally pushed for build-your-own SSO said they won't help us at all investigate the problem. 

This is a stepping stop to get less reliant on ID, so I can actually try to replace ID and Crowd with something else. But allows atlas to work for the time being. 

I don't want things to go straight to ldap for too long, but it's my way of decomposing the problem in a way we can replace the engine without crashing the plane.

**Comment by cintiadr** [comment]
And getting rid of ID in Desk.com was surprisingly hard. Atlas login haven't been working all this time because ID upgrade broke the SSO catastrophically. And really, I won't bother investigating and fixing such problems in a system it's not supported, I have no evidence of its security, it was incredibly unreliable and wasn't production ready when I started taking care of it. 

It's a waste of resources.

**Pull request merged**
